# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\OI\sql\ui\order_detail.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Order_detail(object):
    def setupUi(self, Order_detail):
        Order_detail.setObjectName("Order_detail")
        Order_detail.resize(673, 373)
        self.text2 = QtWidgets.QLabel(Order_detail)
        self.text2.setGeometry(QtCore.QRect(30, 60, 60, 16))
        self.text2.setObjectName("text2")
        self.flytime = QtWidgets.QLabel(Order_detail)
        self.flytime.setGeometry(QtCore.QRect(360, 116, 131, 20))
        self.flytime.setObjectName("flytime")
        self.text3 = QtWidgets.QLabel(Order_detail)
        self.text3.setGeometry(QtCore.QRect(30, 90, 60, 16))
        self.text3.setObjectName("text3")
        self.cabin = QtWidgets.QLabel(Order_detail)
        self.cabin.setGeometry(QtCore.QRect(110, 150, 60, 16))
        self.cabin.setObjectName("cabin")
        self.money = QtWidgets.QLabel(Order_detail)
        self.money.setGeometry(QtCore.QRect(110, 90, 60, 16))
        self.money.setObjectName("money")
        self.starttime = QtWidgets.QLabel(Order_detail)
        self.starttime.setGeometry(QtCore.QRect(210, 100, 131, 16))
        self.starttime.setObjectName("starttime")
        self.text5 = QtWidgets.QLabel(Order_detail)
        self.text5.setGeometry(QtCore.QRect(30, 150, 60, 16))
        self.text5.setObjectName("text5")
        self.input1_3 = QtWidgets.QLabel(Order_detail)
        self.input1_3.setGeometry(QtCore.QRect(360, 100, 131, 16))
        self.input1_3.setObjectName("input1_3")
        self.startend = QtWidgets.QLabel(Order_detail)
        self.startend.setGeometry(QtCore.QRect(210, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.startend.setFont(font)
        self.startend.setObjectName("startend")
        self.passenger_tablewidget = QtWidgets.QTableWidget(Order_detail)
        self.passenger_tablewidget.setGeometry(QtCore.QRect(30, 180, 591, 171))
        self.passenger_tablewidget.setObjectName("passenger_tablewidget")
        self.passenger_tablewidget.setColumnCount(4)
        self.passenger_tablewidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.passenger_tablewidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.passenger_tablewidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.passenger_tablewidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.passenger_tablewidget.setHorizontalHeaderItem(3, item)
        self.flightID = QtWidgets.QLabel(Order_detail)
        self.flightID.setGeometry(QtCore.QRect(110, 120, 60, 16))
        self.flightID.setObjectName("flightID")
        self.text1 = QtWidgets.QLabel(Order_detail)
        self.text1.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text1.setFont(font)
        self.text1.setObjectName("text1")
        self.text4 = QtWidgets.QLabel(Order_detail)
        self.text4.setGeometry(QtCore.QRect(30, 120, 60, 16))
        self.text4.setObjectName("text4")
        self.orderID = QtWidgets.QLabel(Order_detail)
        self.orderID.setGeometry(QtCore.QRect(110, 60, 60, 16))
        self.orderID.setObjectName("orderID")
        self.company = QtWidgets.QLabel(Order_detail)
        self.company.setGeometry(QtCore.QRect(200, 60, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.company.setFont(font)
        self.company.setObjectName("company")
        self.startcity = QtWidgets.QLabel(Order_detail)
        self.startcity.setGeometry(QtCore.QRect(210, 120, 131, 16))
        self.startcity.setObjectName("startcity")
        self.startairport = QtWidgets.QLabel(Order_detail)
        self.startairport.setGeometry(QtCore.QRect(210, 140, 131, 16))
        self.startairport.setObjectName("startairport")
        self.endtime = QtWidgets.QLabel(Order_detail)
        self.endtime.setGeometry(QtCore.QRect(440, 100, 131, 16))
        self.endtime.setObjectName("endtime")
        self.endcity = QtWidgets.QLabel(Order_detail)
        self.endcity.setGeometry(QtCore.QRect(440, 120, 131, 16))
        self.endcity.setObjectName("endcity")
        self.endairport = QtWidgets.QLabel(Order_detail)
        self.endairport.setGeometry(QtCore.QRect(440, 140, 131, 16))
        self.endairport.setObjectName("endairport")

        self.retranslateUi(Order_detail)
        QtCore.QMetaObject.connectSlotsByName(Order_detail)

    def retranslateUi(self, Order_detail):
        _translate = QtCore.QCoreApplication.translate
        Order_detail.setWindowTitle(_translate("Order_detail", "Dialog"))
        self.text2.setText(_translate("Order_detail", "订单号"))
        self.flytime.setText(_translate("Order_detail", "2小时分钟"))
        self.text3.setText(_translate("Order_detail", "订单金额"))
        self.cabin.setText(_translate("Order_detail", "cabin"))
        self.money.setText(_translate("Order_detail", "money"))
        self.starttime.setText(_translate("Order_detail", "06月20日 12:25出发"))
        self.text5.setText(_translate("Order_detail", "舱位类型："))
        self.input1_3.setText(_translate("Order_detail", "飞行"))
        self.startend.setText(_translate("Order_detail", "出发地-目的地（shartend"))
        item = self.passenger_tablewidget.horizontalHeaderItem(0)
        item.setText(_translate("Order_detail", "姓名"))
        item = self.passenger_tablewidget.horizontalHeaderItem(1)
        item.setText(_translate("Order_detail", "乘客类型"))
        item = self.passenger_tablewidget.horizontalHeaderItem(2)
        item.setText(_translate("Order_detail", "证件类型"))
        item = self.passenger_tablewidget.horizontalHeaderItem(3)
        item.setText(_translate("Order_detail", "票号"))
        self.flightID.setText(_translate("Order_detail", "flightID"))
        self.text1.setText(_translate("Order_detail", "已出票"))
        self.text4.setText(_translate("Order_detail", "航班号"))
        self.orderID.setText(_translate("Order_detail", "orderID"))
        self.company.setText(_translate("Order_detail", "（航空公司）（航班号）company"))
        self.startcity.setText(_translate("Order_detail", "杭州"))
        self.startairport.setText(_translate("Order_detail", "萧山机场T1"))
        self.endtime.setText(_translate("Order_detail", "06月20日 12:25出发"))
        self.endcity.setText(_translate("Order_detail", "杭州"))
        self.endairport.setText(_translate("Order_detail", "萧山机场T1"))

